services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: budget-tracker
      POSTGRES_PASSWORD: password

  budget-tracker:
    depends_on: 
      - db
    ports:
      - "8000:8000"
    build: .
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/budget-tracker
